In [2]:
import pyrumba
import time

In [23]:
e = pyrumba.Expr("~v0").solve_poly()
e

(-0x1) + (-0x1) * v0

In [17]:
hex(e.eval([1, 1], 32))

'0xfffffffe'

In [21]:
v0 = 0
v1 = 0
~(-3 * (v0 & v1) - 4 * (v0 & ~v1) + 4 * v0 + 6 * ~(v0 | v1) + 7 * ~(v0 | ~v1) - 6 * ~v0)

-1

In [ ]:
Mismatch for expressions: 0x8 + 0x2 * ((-0x5) & (-0x2) + (-0x1) * v1) + 0x3 * ((-0x5) & v1 + 0x1) + (-0x1) * v1 + (-0x1) * (v0 & v1), 0x1 * ~ (v0 & v1) and vars: [8958, 197, 4944, 3752, 3188, 9057, 9713, 4157, 6280, 1430, 5141, 4490, 2037, 2647, 8064, 7023]


In [6]:

e = pyrumba.Expr(
    "-6*((v1&~v2)|~((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|(~v1&v2)))+2*(v2^~((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|v1))-6*(((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))&v2)^~((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))^(~v1&v2)))+10*~((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|(v1|v2))+14*~((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|(~v1|v2))+2*~(~(1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|(v1|v2))+6*~(~(1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))|(~v1|v2))+12*(~(1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))&(v1&v2))+6*((1*(v4&~v5)+4*v5-3*~(v4^v5)+3*~(v4|v5)-4*~(v4|~v5))&(v1&v2))"
)
e.simplify()

0x2 * (~ v1 & ~ v2 & 0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5)) + 0x2 * (v2 ^ ~ v1 & ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5))) + 0x6 * (v1 & v2 & 0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5)) + 0x6 * (v1 & ~ v2 & 0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5)) + 0xa * (~ v1 & ~ v2 & ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5))) + 0xc * (v1 & v2 & ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5))) + 0xe * (v1 & ~ v2 & ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5))) + (-0x6) * ((v1 | ~ v2) & (v1 | ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) + (-0x3) * ~ (v4 ^ v5) + (v4 & ~ v5))) & (~ v2 | ~ (0x3 * (~ v4 & ~ v5) + 0x4 * v5 + (-0x4) * (v5 & ~ v4) 

In [14]:
pyrumba.Expr("v0 | v1").solve_poly()

v0 + v1 + (-0x1) * (v0 & v1)

In [7]:
r = e.solve_non_poly()
r

0x0 + 0x2 * v4 + 0x4 * v2 + 0x4 * v2 * v4 + 0x4 * v4 * (v1 & v2) + 0x6 * (v1 & v4) + 0x6 * (v1 & (-0x1) + (-0x1) * v2 + (-0x1) * v4 + (-0x1) * (v1 & v2 & v4) + (v1 & v2) + (v2 & v4)) + 0xc * (v1 & v2 & (-0x1) + (-0x1) * v4) + 0xc * ((-0x1) + 0x2 * (v2 & v4) + (-0x2) * (v1 & v2 & v4) + (-0x1) * v2 + (-0x1) * v4 + (v1 & v2) & v2 * v4) + 0x14 * (v1 & v2 & v4) + (-0x14) * (v2 & v4) + (-0xa) * (v1 & v2) + (-0x6) * (v1 & v2 & (-0x1) + (-0x1) * v2 + (-0x1) * v4 + (-0x1) * (v1 & v2 & v4) + (v1 & v2) + (v2 & v4)) + (-0x4) * v1 + (-0x4) * (v2 & (-0x1) + (-0x1) * v1 + (-0x1) * v4 + (v1 & v4)) + (-0x4) * v1 * v4

In [10]:
r.__debug__()

'Add([Const(340282366920938463371140887063220453376), Scale(2, Var(4)), Scale(4, Var(2)), Scale(4, Mul([Var(2), Var(4)])), Scale(4, Mul([Var(4), And([Var(1), Var(2)])])), Scale(6, And([Var(1), Var(4)])), Scale(6, And([Var(1), Add([Const(340282366920938463463374607431768211455), Scale(18446744073709551615, Var(2)), Scale(18446744073709551615, Var(4)), Scale(18446744073709551615, And([Var(1), Var(2), Var(4)])), And([Var(1), Var(2)]), And([Var(2), Var(4)])])])), Scale(12, And([Var(1), Var(2), Add([Const(340282366920938463463374607431768211455), Scale(18446744073709551615, Var(4))])])), Scale(12, And([Add([Const(340282366920938463463374607431768211455), Scale(2, And([Var(2), Var(4)])), Scale(18446744073709551614, And([Var(1), Var(2), Var(4)])), Scale(18446744073709551615, Var(2)), Scale(18446744073709551615, Var(4)), And([Var(1), Var(2)])]), Mul([Var(2), Var(4)])])), Scale(20, And([Var(1), Var(2), Var(4)])), Scale(18446744073709551596, And([Var(2), Var(4)])), Scale(18446744073709551606, An

In [11]:
e = pyrumba.Expr("(-0x4) * (v2 & (-0x1) + (v1 & v4) + (-0x1) * v1 + (-0x1) * v4)")
e.simplify()

(-0x4) * (v2 & (-0x1) + (-0x1) * v1 + (-0x1) * v4 + (v1 & v4))

# Prove equivalences

In [36]:
for x in range(5):
    print(f"{x}: {~((~x) + 2)} vs {x - 2}")

0: -2 vs -2
1: -1 vs -1
2: 0 vs 0
3: 1 vs 1
4: 2 vs 2


In [44]:
for x in range(5):
    print(f"{x}: {(~x) + 2}")

0: 1
1: 0
2: -1
3: -2
4: -3


In [42]:
2 & (- 2)

2

In [50]:
for x in [0, 1]:
    for y in [0, 1]:
        print(f"{x, y}: {(y ^ ((~x) + 2))} vs {(y ^ (~x)) - 2 * (0 ^ (~0))}")

(0, 0): 1 vs 1
(0, 1): 0 vs 0
(1, 0): 0 vs 0
(1, 1): 1 vs 1


In [ ]:
def f ( x ):
    v0 = x *0xe5 + 0xF7
    v0 = v0 & 0xFF
    v3 = ((((( v0 * 0x26 ) + 0x55 ) & 0xFE ) + ( v0 * 0xED ) + 0xD6 ) & 0xFF )
    v4 = (((((( - ( v3 * 0x2 )) + 0xFF ) & 0xFE ) + v3 ) * 0x03 ) + 0x4D )
    v5 = ((((( v4 * 0x56 ) + 0x24 ) & 0x46 ) * 0x4B ) + ( v4 * 0xE7 ) + 0x76 )
    v7 = (((( v5 * 0x3A ) + 0xAF ) & 0xF4 ) + ( v5 * 0x63 ) + 0x2E )
    v6 = ( v7 & 0x94 )
    v8 = (((( v6 + v6 + ( - ( v7 & 0xFF ))) * 0x67 ) + 0xD ))
    res = (( v8 * 0x2D )+((( v8 * 0xAE ) | 0x22 ) * 0xE5 ) + 0xC2 ) & 0xFF
    return (0xed * ( res -0xF7 )) & 0xff

In [17]:
X = pyrumba.PyANFExpr.var(1, 8)
f(X) == X ^ 0x5C

NameError: name 'f' is not defined

In [3]:
X = pyrumba.Expr.var(1)

In [4]:
f(X).size()

913

In [21]:
pyrumba.PyExpr("v0 + v1")

v0+v1

In [7]:
fx = f(X)
fx.simplify()
fx.size()

866

In [ ]:
fx.anf(8) == mba.PyANFExpr.var(1, 8) ^ 0x5C

TypeError: Operand must be ANFExpr or int

# Reasonable performances...

In [13]:
start = time.perf_counter()
X = mba.PyANFExpr.var(1, 8)
C = f(X)
end = time.perf_counter()
elapsed = (end - start) * 1000
print(f"Found result in {elapsed:.6f}ms")

Found result in 704.965185ms


In [14]:
C == X ^ 0x5C

True

In [15]:
X = mba.PyANFExpr.var(1, 64)

start = time.perf_counter()
C = ((~X | 0x7AFAFA697AFAFA69) & 0xA061440A061440) + ((X & 0x10401050504) | 0x1010104)
end = time.perf_counter()
elapsed = (end - start) * 1000
print(f"Found {hex(C.to_int())} in {elapsed:.6f}ms")

Found 0xa061440b071544 in 1.301481ms


# Bad Performances...

These symbolic expressions are very _very_ large

In [16]:
X = mba.PyANFExpr.var(0, 8)
Y = mba.PyANFExpr.var(1, 8)

In [17]:
(X + Y).size()

1554

In [18]:
(X - Y).size()

15868

In [19]:
(X * Y).size()

10262

Of course the problem worsens when $n$ increases

In [20]:
X = mba.PyANFExpr.var(0, 16)
Y = mba.PyANFExpr.var(1, 16)

In [21]:
(X + Y).size()

917538

# Sandbox

In [ ]:
X = mba.PyANFExpr.var(0, 8)
Y = mba.PyANFExpr.var(1, 8)

e1 = (X ^ Y) + 2 * (X & Y)
e2 = e1 * 39 + 23
E = e2 * 151 + 111

In [2]:
X = mba.PyANFExpr.var(0, 8)
e2 = X * 39 + 23
E = e2 * 151 + 111
X == E

True

In [ ]:
v0 = mba.PyANFExpr.var(0, 2)
v1 = mba.PyANFExpr.var(1, 2)

assert((v0 + v1)[1] == ((v0[0] & v1[0]) ^ v0[1] ^ v1[1]))
assert((v0 | v1)[1] == ((v0[1] & v1[1]) ^ v0[1] ^ v1[1]))

In [12]:
(v0 + v1)[1]

((v0_0 & v1_0) ^ v0_1 ^ v1_1)

In [13]:
(v0 | v1)[1]

((v0_1 & v1_1) ^ v0_1 ^ v1_1)

In [6]:
v0 = 42
v1 = 69

(
    (v0 & v1) * (v0 & v1) * 225
    + (v0 & v1) * (v0 ^ v1) * 105
    + (v0 & v1) * v1 * (-105)
    + (v0 & v1) * v0 * (-105)
    + (v0 ^ v1) * (v0 & v1) * 105
    + (v0 ^ v1) * (v0 ^ v1) * 49
    + (v0 ^ v1) * v1 * (-49)
    + (v0 ^ v1) * v0 * (-49)
    + v1 * (v0 & v1) * (-105)
    + v1 * (v0 ^ v1) * (-49)
    + v1 * v1 * 49
    + v1 * v0 * 49
    + v0 * (v0 & v1) * (-105)
    + v0 * (v0 ^ v1) * (-49)
    + v0 * v1 * 49
    + v0 * v0 * 49
)

0

In [14]:
v0 = 42
v1 = 70

print(~v1 * ~v1 * 56 + ~v1 * ~v0 * (-56) + ~v1 * v1 * 56 + ~v1 * v0 * (-56) + ~v0 * ~v1 * (-56) + ~v0 * ~v0 * 56 + ~v0 * v1 * (-56) + ~v0 * v0 * 56 + v1 * ~v1 * 56 + v1 * ~v0 * (-56) + v1 * v1 * 56 + v1 * v0 * (-56) + v0 * ~v1 * (-56) + v0 * ~v0 * 56 + v0 * v1 * (-56) + v0 * v0 * 56 + v0)

42


In [15]:
v0 + v1, 2* v0 + ~v0 - ~ v1

(112, 112)

In [23]:
from z3 import *
v0 = BitVec("v0", 16)
v1 = BitVec("v1", 16)

In [24]:
S = ~v1 * ~v1 * 9 + ~v1 * ~v0 * (-9) + ~v1 * v1 * 9 + ~v1 * v0 * (-9) + ~v0 * ~v1 * (-9) + ~v0 * ~v0 * 9 + ~v0 * v1 * (-9) + ~v0 * v0 * 9 + v1 * ~v1 * 9 + v1 * ~v0 * (-9) + v1 * v1 * 9 + v1 * v0 * (-9) + v0 * ~v1 * (-9) + v0 * ~v0 * 9 + v0 * v1 * (-9) + v0 * v0 * 9

In [25]:
simplify(S)

9*~v1*~v1 +
65518*~v0*~v1 +
18*v1*~v1 +
65518*v0*~v1 +
9*~v0*~v0 +
65518*v1*~v0 +
18*v0*~v0 +
9*v1*v1 +
65518*v0*v1 +
9*v0*v0

In [26]:
256 * 256

65536

In [ ]:
11*v1-1*!(v0^v1)-3*(v0|v1)-2*!(v0&!v1)-3*!(v0&!v0)+3*(v0^v1)-1*(v0|!v1)+7*!(v0|v1)-6*!(v0|!v1)+9*(v0&!v1)+4*(v0&v1)

In [36]:
bin(-30064771072)[::-1][32:]

'111b0-'

In [ ]:
11 * y - 1 * ~(x ^ y) - 3 * (x | y) - 2 * ~(x & ~y) - 3 * ~(x & ~x) + 3 * (
    x ^ y
) - 1 * (x | ~y) + 7 * ~(x | y) - 6 * ~(x | ~y) + 9 * (x & ~y) + 4 * (
    x & y
),

In [39]:
bin(~1)

'-0b10'

In [3]:
bin(4294967294)

'0b11111111111111111111111111111110'

In [10]:
import random

for _ in range(100):
    v0 = random.randint(0, 1024)
    v1 = random.randint(0, 1024)
    print(
        (v0 * 782850609),
        (v0 & 0xD156A5CE) * (~v0 & 0x2EA95A31) + (v0 | 0x2EA95A31) * (v0 & 0x2EA95A31),
    )

428219283123 428219283123
670120121304 670120121304
335842911261 335842911261
118993292568 118993292568
61845198111 61845198111
699085593837 699085593837
158135823018 158135823018
8611356699 8611356699
772673551083 772673551083
40708231668 40708231668
67325152374 67325152374
159701524236 159701524236
308443139946 308443139946
785982011436 785982011436
272432011932 272432011932
701434145664 701434145664
627063337809 627063337809
317837347254 317837347254
112730487696 112730487696
444659145912 444659145912
38359679841 38359679841
177707088243 177707088243
497892987324 497892987324
601229267712 601229267712
390642453891 390642453891
439179191649 439179191649
443093444694 443093444694
77502210291 77502210291
494761584888 494761584888
181621341288 181621341288
665423017650 665423017650
125256097440 125256097440
742142377332 742142377332
37576829232 37576829232
682645731048 682645731048
502590090978 502590090978
766410746211 766410746211
329580106389 329580106389
202758307731 202758307731
72

In [ ]:
(v0 & !v1) * (!v0 & v1) + (v0 | v1) * (v0 & v1)

In [31]:
import numpy as np

# Example vectors of size 4
one = np.array([1, 1, 1, 1])
x = np.array([0, 0, 1, 1])
y = np.array([0, 1, 0, 1])
xy = np.array([0, 0, 0, 1])

def band(x, y):
    return np.bitwise_and(x, y)


def outer(x, y):
    return band(
        np.matrix([
            [x[j] * y[i] for i in range(4)] for j in range(4)
        ]),
        np.matrix([
            [x[i] * y[j] for i in range(4)] for j in range(4)
        ])
    )

times_one = lambda x: np.outer(x, one) + np.outer(one, x)

# Symmetrized outer product
One = times_one(one)
X   = times_one(x)
Y   = times_one(y)
XY  = times_one(xy)

print(One)
print(X)
print(Y)
print(XY)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[0 0 1 1]
 [0 0 1 1]
 [1 1 2 2]
 [1 1 2 2]]
[[0 1 0 1]
 [1 2 1 2]
 [0 1 0 1]
 [1 2 1 2]]
[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [1 1 1 2]]


In [32]:
X * Y

array([[0, 0, 0, 1],
       [0, 0, 1, 2],
       [0, 1, 0, 2],
       [1, 2, 2, 4]])

In [26]:
outer(x, y)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1]])

In [20]:
np.matrix([[1, 0], [0, 1]])

matrix([[1, 0],
        [0, 1]])

In [ ]:
v0 = 0
v1 = 0

In [40]:
for (v0, v1) in [(i, j) for i in range(2) for j in range(2)]:
    print(-34*~v1*(v0&v1)-36*~v1*(v0&~v1)+12*~v1*~(v0&v1)+10*~v1*~(v0^v1)-24*~v1*~(v0|v1)-36*~v1*~(v0|~v1)+17*v1*(v0&v1)+18*v1*(v0&~v1)-6*v1*~(v0&v1)-5*v1*~(v0^v1)+12*v1*~(v0|v1)+18*v1*~(v0|~v1)+22*~v1*(v0|v1)-11*v1*(v0|v1))

-2
-5
-2
-5


In [43]:
for (v0, v1) in [(i, j) for i in range(2) for j in range(2)]:
    print((-2) + 3 * v1)

-2
1
-2
1


In [47]:
l = []
with open("test.txt") as f:
    l = list(map(lambda x: x.split(","), f.readlines()))

In [48]:
l[0]

['-1*y+1*~(x|y)+1*(x&y)',
 '1*~y-1*(x^y)',
 '-8*~y*(x&y)-8*~y*(x&~y)+10*~y*x+3*~y*~(x|y)+8*(x^y)*(x&y)+8*(x^y)*(x&~y)-10*(x^y)*x-3*(x^y)*~(x|y)-3*~y*(x|~y)-1*~y*~x+3*(x^y)*(x|~y)+1*(x^y)*~x\n']

In [52]:
def vectorize(s):
    out = [0, 0, 0, 0]
    for i in range(4):
        out[i] = eval(s, {
            "x": i // 2,
            "y": i % 2
        })
    return out

In [ ]:
def vectorize(s):
    out = [0, 0, 0, 0]
    for i in range(4):
        out[i] = eval(s, {"x": i // 2, "y": i % 2})
    return out

def test_hyp(e1, e2):
    return vectorize(e1) == vectorize(e2)


c = 0
for x in l:
    if 'z' in x[2]:
        continue
    c += 1
    assert(vectorize(x[1]) == vectorize(x[2]))
c

516

In [59]:
for x in range(5):
    print(f"{x}: {(~x) * x + x * x}")

0: 0
1: -1
2: -2
3: -3
4: -4


In [56]:
for x in range(2):
    for y in range(2):
        print(f"{x,y}: {(~x) & y}")

(0, 0): 0
(0, 1): 1
(1, 0): 0
(1, 1): 0


In [52]:
x = 5
(~x) * x + x * x - x

-10

In [1]:
hex(4294967295)

'0xffffffff'

In [8]:
x = mba.PyExpr.var(0)
y = mba.PyExpr.var(1)
(1 * (x | y) + 3 * y - 4 * ~(x | ~y) + 6 * (x & ~y) + 3 * (x & y)) * (
    1 * (x | y) + 3 * y - 4 * ~(x | ~y) + 6 * (x & ~y) + 3 * (x & y)
)

(((((((v0 | v1) * 1) + (v1 * 3)) - (!(v0 | !v1) * 4)) + ((v0 & !v1) * 6)) + ((v0 & v1) * 3)) * ((((((v0 | v1) * 1) + (v1 * 3)) - (!(v0 | !v1) * 4)) + ((v0 & !v1) * 6)) + ((v0 & v1) * 3)))

In [12]:
(1 * (x | y) + 3 * y - 4 * ~(x | ~y) + 6 * (x & ~y) + 3 * (x & y)) *(
    -(4 * y * (x & y))
    - 1 * y * (x & ~y)
    + 14 * y * ~(x ^ y)
    - 22 * y * ~(x | y)
    + 3 * y * ~(x | ~y)
    - 11 * y * y
    + 7 * y * ~x
)

(((((((v0 | v1) * 1) + (v1 * 3)) - (!(v0 | !v1) * 4)) + ((v0 & !v1) * 6)) + ((v0 & v1) * 3)) * ((((((-((v1 * 4) * (v0 & v1)) - ((v1 * 1) * (v0 & !v1))) + ((v1 * 14) * !(v0 ^ v1))) - ((v1 * 22) * !(v0 | v1))) + ((v1 * 3) * !(v0 | !v1))) - ((v1 * 11) * v1)) + ((v1 * 7) * !v0)))

In [ ]:
cargo run --bin rumba -- "-34*~v1*(v0&v1)-36*~v1*(v0&~v1)+12*~v1*~(v0&v1)+10*~v1*~(v0^v1)-24*~v1*~(v0|v1)-36*~v1*~(v0|~v1)+17*v1*(v0&v1)+18*v1*(v0&~v1)-6*v1*~(v0&v1)-5*v1*~(v0^v1)+12*v1*~(v0|v1)+18*v1*~(v0|~v1)+22*~v1*(v0|v1)-11*v1*(v0|v1)" --test

In [15]:
v0 = 1
v1 = 1
-34*~v1*(v0&v1)-36*~v1*(v0&~v1)+12*~v1*~(v0&v1)+10*~v1*~(v0^v1)-24*~v1*~(v0|v1)-36*~v1*~(v0|~v1)+17*v1*(v0&v1)+18*v1*(v0&~v1)-6*v1*~(v0&v1)-5*v1*~(v0^v1)+12*v1*~(v0|v1)+18*v1*~(v0|~v1)+22*~v1*(v0|v1)-11*v1*(v0|v1)

-5

In [ ]:
-1*(-1*(v0&v1)+2*(v0|~v1)+1*~(v0|~v1)-2*~v1)+1*~(v0|v1)+1*(v0&(-1*(v0&v1)+2*(v0|~v1)+1*~(v0|~v1)-2*~v1))

In [6]:
import numpy as np

m = 4  # dimension of each vector
# all nonzero binary vectors of length m
D = np.array(
    [[int(x) for x in format(i, f"0{m}b")] for i in range(1, 2**m)]
).T  # shape (m, 2**m - 1)

# normalize columns
D = D / np.linalg.norm(D, axis=0, keepdims=True)

print(D)

# compute mutual coherence
G = D.T @ D
np.fill_diagonal(G, 0)
mu = np.max(np.abs(G))
spark_lb = 1 + 1 / mu

print(f"D shape: {D.shape}")
print(f"Mutual coherence: {mu:.3f}")
print(f"Spark lower bound: {spark_lb:.2f}")

[[0.         0.         0.         0.         0.         0.
  0.         1.         0.70710678 0.70710678 0.57735027 0.70710678
  0.57735027 0.57735027 0.5       ]
 [0.         0.         0.         1.         0.70710678 0.70710678
  0.57735027 0.         0.         0.         0.         0.70710678
  0.57735027 0.57735027 0.5       ]
 [0.         1.         0.70710678 0.         0.         0.70710678
  0.57735027 0.         0.         0.70710678 0.57735027 0.
  0.         0.57735027 0.5       ]
 [1.         0.         0.70710678 0.         0.70710678 0.
  0.57735027 0.         0.70710678 0.         0.57735027 0.
  0.57735027 0.         0.5       ]]
D shape: (4, 15)
Mutual coherence: 0.866
Spark lower bound: 2.15


In [60]:
y ^ x & (y | -(y | -(x | y)))

5

In [ ]:
for x in range(5):
    for y in range(5):
        print(f"{x,y}: {x & (y | -(y | -(x | y)))}")

(0, 0): 0
(0, 1): 1
(0, 2): 2
(0, 3): 3
(0, 4): 4
(1, 0): 1
(1, 1): 1
(1, 2): 3
(1, 3): 3
(1, 4): 5
(2, 0): 2
(2, 1): 3
(2, 2): 2
(2, 3): 3
(2, 4): 6
(3, 0): 3
(3, 1): 3
(3, 2): 3
(3, 3): 3
(3, 4): 7
(4, 0): 4
(4, 1): 5
(4, 2): 6
(4, 3): 7
(4, 4): 4
